### ISSUE TITLE
[meta] Ray Tracing

### ISSUE THREAD

**Issue by kvark** [kvark/blade#6]
Stage I:
- [ ] Vulkan wrapper around acceleration structures
- [ ] Fix `naga` SPIRV-1.4 target
- [ ] Add `naga` support for ray queries
- [ ] Example

Stage II:
- [ ] Vulkan wrapper around RT pipelines
- [ ] Add `naga` support for RT shader stages
- [ ] Example

Stage III:
- [ ] Metal support for acceleration structures and RT pipelines
- [ ] `naga` MSL support for ray queries and RT shader stages
- [ ] Make RT examples portable
